<?php


namespace app\components;


use yii\base\Widget;

class HelloWidget extends Widget
{
    public $name;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if ($this->name===null){
            $this->name = 'Гость';
        }
        ob_start();
    }

    public function run()
    {
        $content = ob_get_clean();
        $content = strip_tags($content);
        return $this->render('hello',[
            'name'=>$this->name,
            'content'=>$content,
        ]);
        //return "Привет, {$this->name}! {$content}";

    }
}